[server]
# Maximum message size in MB (20480 MB = 20GB)
maxMessageSize = 20480

# Enable file server
enableXsrfProtection = true

[client]
# Maximum upload size in MB (20480 MB = 20GB)
maxUploadSize = 20480

[theme]
base = "dark"
primaryColor = "#1f77b4"
